apiVersion: v1
kind: Service
metadata:
  labels:
    run: nfs-svc
  name: nfs-svc
spec:
  clusterIP: 10.102.161.60
  ports:
  - port: 111 
    name: tcp111
    protocol: TCP
    targetPort: tcp111
  - port: 111 
    name: udp111
    protocol: UDP
    targetPort: udp111
  - port: 2049 
    name: tcp2049
    protocol: TCP
    targetPort: tcp2049
  - port: 2049 
    name: udp2049
    protocol: UDP
    targetPort: udp2049
  - port: 32765 
    name: tcp32765
    protocol: TCP
    targetPort: tcp32765
  - port: 32765 
    name: udp32765
    protocol: UDP
    targetPort: udp32765
  - port: 32766 
    name: tcp32766
    protocol: TCP
    targetPort: tcp32766
  - port: 32766 
    name: udp32766
    protocol: UDP
    targetPort: udp32766
  - port: 32767 
    name: tcp32767
    protocol: TCP
    targetPort: tcp32767
  - port: 32767 
    name: udp32767
    protocol: UDP
    targetPort: udp32767
  selector:
    app: nfs
  type: ClusterIP
