apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-11-29T03:14:44Z"
  labels:
    run: my-web-ssh-server01
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:run: {}
      f:spec:
        f:containers:
          k:{"name":"my-web-ssh-server01"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kubectl-run
    operation: Update
    time: "2022-11-29T03:14:44Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.244.1.45"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2022-11-29T03:14:45Z"
  name: my-web-ssh-server01
  namespace: default
  resourceVersion: "25916906"
  selfLink: /api/v1/namespaces/default/pods/my-web-ssh-server01
  uid: 39e8c9c3-a041-431f-973d-e75669e98129
spec:
  containers:
  - image: my_web_ssh:22.1.31
    imagePullPolicy: IfNotPresent
    name: my-web-ssh-server01
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-k27kh
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-k27kh
    secret:
      defaultMode: 420
      secretName: default-token-k27kh
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-11-29T03:14:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-11-29T03:14:45Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-11-29T03:14:45Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-11-29T03:14:44Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://62143e27ee6731c2e0f6e5fb1085919aed4987671b5b7086e842136d02872b6d
    image: my_web_ssh:22.1.31
    imageID: docker://sha256:5b3b04be3b6b21b035e204d999e8847249e11ba4c5c87e2b9511777d0ee7ad27
    lastState: {}
    name: my-web-ssh-server01
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-11-29T03:14:44Z"
  hostIP: 172.30.2.61
  phase: Running
  podIP: 10.244.1.45
  podIPs:
  - ip: 10.244.1.45
  qosClass: BestEffort
  startTime: "2022-11-29T03:14:44Z"
