apiVersion: v1
kind: Service
metadata:
  labels:
    run: mysql-svc
  name: mysql-svc
spec:
  clusterIP: 10.102.161.40
  ports:
  - port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: mysql
  type: ClusterIP
