apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: php-pod
  name: php-svc
spec:
  clusterIP: 10.102.161.30
  ports:
  - port: 9000
    protocol: TCP
    targetPort: php
  selector:
    app: php
  type: ClusterIP
status:
  loadBalancer: {}
