apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: php-pod
  name: php-api-pod
spec:
#  nodeSelector:
#    php: true
  shareProcessNamespace: true
  volumes:
    - name: data-vol
      hostPath: 
        path: "/data/www"
        type: DirectoryOrCreate
    - name: ini-vol
      hostPath: 
        path: "/data/php/conf.d/php.ini"
        type: FileOrCreate           
  containers:
  - image: webdevops/php:latest
    imagePullPolicy: IfNotPresent
    name: php-c   
    ports:
    - name: php
      containerPort: 9000 
    volumeMounts:
    - mountPath: /usr/share/nginx/www 
      name: data-vol 
    - mountPath: /etc/php/7.2/cli/php.ini  
      name: ini-vol
  - image: busybox:latest        
    imagePullPolicy: IfNotPresent
    name: busybox-c
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
