apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: php-dpl
  name: php-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-dpl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: php-dpl
    spec:
      containers:
      - image: php
        name: php
        resources: {}
status: {}
