apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-pod
spec:
#  nodeSelector:
#    nginx: true
  shareProcessNamespace: true
  volumes:
    - name: www-vol
      hostPath: 
        path: "/data/www"
        type: DirectoryOrCreate
    - name: conf-vol
      hostPath: 
        path: "/data/nginx/conf.d/default.conf"
        type: FileOrCreate           
    - name: log-vol
      hostPath: 
        path: "/data/nginx/log"
        type: DirectoryOrCreate
  containers:
  - image: nginx:latest   
    name: nginx-c   
    imagePullPolicy: IfNotPresent
    ports:
    - name: nginx
      containerPort: 80 
    volumeMounts:
    - mountPath: /usr/share/nginx/www 
      name: www-vol 
    - mountPath: /etc/nginx/conf.d/default.conf 
      name: conf-vol
    - mountPath: /var/log/nginx                       
      name: log-vol
  - image: busybox:latest        
    name: busybox-c
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
