apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-svc
spec:
  ports:
  - port: 80
    nodePort: 31656
    protocol: TCP
    targetPort: nginx
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
